from elasticsearch import Elasticsearch
import json

def load(s):
    try:
        print "trying %s" % s
        json.loads(s)
    except:
        print "Couldn't decode `%s`" % s
        raise

def main(draft_data):
    es_index = 'vtest'
    es_type = 'lottery'

    inserts = ""
    for l in draft_data.split("\n"):
        if not l: continue
        inserts += "{\"index\":{\"_index\":\"%s\",\"_type\":\"%s\"}}\n%s\n" % \
            (es_index, es_type, l)
        
    es = Elasticsearch()
    if es.indices.exists(index=es_index):
      es.indices.delete(index=es_index)
      import time
      time.sleep(2)
      es.indices.create(index=es_index,
                        body={
                          "mappings": {
                            es_type: {
                              "properties": {
                                "Day": {"type":"integer"},
                                "Day_of_year": {"type":"integer"},
                                "Draft_No.": {"type":"integer"},
                                "Mo.Number": {"type":"integer"}
                              }
                            }
                          }
                        })

    es.bulk(index=es_index, doc_type=es_type, body=inserts)

draft_data = """
{"Day":"1","Month":"Jan","Mo.Number":"1","Day_of_year":"1","Draft_No.":"305"}
{"Day":"2","Month":"Jan","Mo.Number":"1","Day_of_year":"2","Draft_No.":"159"}
{"Day":"3","Month":"Jan","Mo.Number":"1","Day_of_year":"3","Draft_No.":"251"}
{"Day":"4","Month":"Jan","Mo.Number":"1","Day_of_year":"4","Draft_No.":"215"}
{"Day":"5","Month":"Jan","Mo.Number":"1","Day_of_year":"5","Draft_No.":"101"}
{"Day":"6","Month":"Jan","Mo.Number":"1","Day_of_year":"6","Draft_No.":"224"}
{"Day":"7","Month":"Jan","Mo.Number":"1","Day_of_year":"7","Draft_No.":"306"}
{"Day":"8","Month":"Jan","Mo.Number":"1","Day_of_year":"8","Draft_No.":"199"}
{"Day":"9","Month":"Jan","Mo.Number":"1","Day_of_year":"9","Draft_No.":"194"}
{"Day":"10","Month":"Jan","Mo.Number":"1","Day_of_year":"10","Draft_No.":"325"}
{"Day":"11","Month":"Jan","Mo.Number":"1","Day_of_year":"11","Draft_No.":"329"}
{"Day":"12","Month":"Jan","Mo.Number":"1","Day_of_year":"12","Draft_No.":"221"}
{"Day":"13","Month":"Jan","Mo.Number":"1","Day_of_year":"13","Draft_No.":"318"}
{"Day":"14","Month":"Jan","Mo.Number":"1","Day_of_year":"14","Draft_No.":"238"}
{"Day":"15","Month":"Jan","Mo.Number":"1","Day_of_year":"15","Draft_No.":"17"}
{"Day":"16","Month":"Jan","Mo.Number":"1","Day_of_year":"16","Draft_No.":"121"}
{"Day":"17","Month":"Jan","Mo.Number":"1","Day_of_year":"17","Draft_No.":"235"}
{"Day":"18","Month":"Jan","Mo.Number":"1","Day_of_year":"18","Draft_No.":"140"}
{"Day":"19","Month":"Jan","Mo.Number":"1","Day_of_year":"19","Draft_No.":"58"}
{"Day":"20","Month":"Jan","Mo.Number":"1","Day_of_year":"20","Draft_No.":"280"}
{"Day":"21","Month":"Jan","Mo.Number":"1","Day_of_year":"21","Draft_No.":"186"}
{"Day":"22","Month":"Jan","Mo.Number":"1","Day_of_year":"22","Draft_No.":"337"}
{"Day":"23","Month":"Jan","Mo.Number":"1","Day_of_year":"23","Draft_No.":"118"}
{"Day":"24","Month":"Jan","Mo.Number":"1","Day_of_year":"24","Draft_No.":"59"}
{"Day":"25","Month":"Jan","Mo.Number":"1","Day_of_year":"25","Draft_No.":"52"}
{"Day":"26","Month":"Jan","Mo.Number":"1","Day_of_year":"26","Draft_No.":"92"}
{"Day":"27","Month":"Jan","Mo.Number":"1","Day_of_year":"27","Draft_No.":"355"}
{"Day":"28","Month":"Jan","Mo.Number":"1","Day_of_year":"28","Draft_No.":"77"}
{"Day":"29","Month":"Jan","Mo.Number":"1","Day_of_year":"29","Draft_No.":"349"}
{"Day":"30","Month":"Jan","Mo.Number":"1","Day_of_year":"30","Draft_No.":"164"}
{"Day":"31","Month":"Jan","Mo.Number":"1","Day_of_year":"31","Draft_No.":"221"}
{"Day":"1","Month":"Feb","Mo.Number":"2","Day_of_year":"32","Draft_No.":"86"}
{"Day":"2","Month":"Feb","Mo.Number":"2","Day_of_year":"33","Draft_No.":"144"}
{"Day":"3","Month":"Feb","Mo.Number":"2","Day_of_year":"34","Draft_No.":"297"}
{"Day":"4","Month":"Feb","Mo.Number":"2","Day_of_year":"35","Draft_No.":"210"}
{"Day":"5","Month":"Feb","Mo.Number":"2","Day_of_year":"36","Draft_No.":"214"}
{"Day":"6","Month":"Feb","Mo.Number":"2","Day_of_year":"37","Draft_No.":"347"}
{"Day":"7","Month":"Feb","Mo.Number":"2","Day_of_year":"38","Draft_No.":"91"}
{"Day":"8","Month":"Feb","Mo.Number":"2","Day_of_year":"39","Draft_No.":"181"}
{"Day":"9","Month":"Feb","Mo.Number":"2","Day_of_year":"40","Draft_No.":"338"}
{"Day":"10","Month":"Feb","Mo.Number":"2","Day_of_year":"41","Draft_No.":"216"}
{"Day":"11","Month":"Feb","Mo.Number":"2","Day_of_year":"42","Draft_No.":"150"}
{"Day":"12","Month":"Feb","Mo.Number":"2","Day_of_year":"43","Draft_No.":"68"}
{"Day":"13","Month":"Feb","Mo.Number":"2","Day_of_year":"44","Draft_No.":"152"}
{"Day":"14","Month":"Feb","Mo.Number":"2","Day_of_year":"45","Draft_No.":"4"}
{"Day":"15","Month":"Feb","Mo.Number":"2","Day_of_year":"46","Draft_No.":"89"}
{"Day":"16","Month":"Feb","Mo.Number":"2","Day_of_year":"47","Draft_No.":"212"}
{"Day":"17","Month":"Feb","Mo.Number":"2","Day_of_year":"48","Draft_No.":"189"}
{"Day":"18","Month":"Feb","Mo.Number":"2","Day_of_year":"49","Draft_No.":"292"}
{"Day":"19","Month":"Feb","Mo.Number":"2","Day_of_year":"50","Draft_No.":"25"}
{"Day":"20","Month":"Feb","Mo.Number":"2","Day_of_year":"51","Draft_No.":"302"}
{"Day":"21","Month":"Feb","Mo.Number":"2","Day_of_year":"52","Draft_No.":"363"}
{"Day":"22","Month":"Feb","Mo.Number":"2","Day_of_year":"53","Draft_No.":"290"}
{"Day":"23","Month":"Feb","Mo.Number":"2","Day_of_year":"54","Draft_No.":"57"}
{"Day":"24","Month":"Feb","Mo.Number":"2","Day_of_year":"55","Draft_No.":"236"}
{"Day":"25","Month":"Feb","Mo.Number":"2","Day_of_year":"56","Draft_No.":"179"}
{"Day":"26","Month":"Feb","Mo.Number":"2","Day_of_year":"57","Draft_No.":"365"}
{"Day":"27","Month":"Feb","Mo.Number":"2","Day_of_year":"58","Draft_No.":"205"}
{"Day":"28","Month":"Feb","Mo.Number":"2","Day_of_year":"59","Draft_No.":"299"}
{"Day":"29","Month":"Feb","Mo.Number":"2","Day_of_year":"60","Draft_No.":"285"}
{"Day":"1","Month":"Mar","Mo.Number":"3","Day_of_year":"61","Draft_No.":"108"}
{"Day":"2","Month":"Mar","Mo.Number":"3","Day_of_year":"62","Draft_No.":"29"}
{"Day":"3","Month":"Mar","Mo.Number":"3","Day_of_year":"63","Draft_No.":"267"}
{"Day":"4","Month":"Mar","Mo.Number":"3","Day_of_year":"64","Draft_No.":"275"}
{"Day":"5","Month":"Mar","Mo.Number":"3","Day_of_year":"65","Draft_No.":"293"}
{"Day":"6","Month":"Mar","Mo.Number":"3","Day_of_year":"66","Draft_No.":"139"}
{"Day":"7","Month":"Mar","Mo.Number":"3","Day_of_year":"67","Draft_No.":"122"}
{"Day":"8","Month":"Mar","Mo.Number":"3","Day_of_year":"68","Draft_No.":"213"}
{"Day":"9","Month":"Mar","Mo.Number":"3","Day_of_year":"69","Draft_No.":"317"}
{"Day":"10","Month":"Mar","Mo.Number":"3","Day_of_year":"70","Draft_No.":"323"}
{"Day":"11","Month":"Mar","Mo.Number":"3","Day_of_year":"71","Draft_No.":"136"}
{"Day":"12","Month":"Mar","Mo.Number":"3","Day_of_year":"72","Draft_No.":"300"}
{"Day":"13","Month":"Mar","Mo.Number":"3","Day_of_year":"73","Draft_No.":"259"}
{"Day":"14","Month":"Mar","Mo.Number":"3","Day_of_year":"74","Draft_No.":"354"}
{"Day":"15","Month":"Mar","Mo.Number":"3","Day_of_year":"75","Draft_No.":"169"}
{"Day":"16","Month":"Mar","Mo.Number":"3","Day_of_year":"76","Draft_No.":"166"}
{"Day":"17","Month":"Mar","Mo.Number":"3","Day_of_year":"77","Draft_No.":"33"}
{"Day":"18","Month":"Mar","Mo.Number":"3","Day_of_year":"78","Draft_No.":"332"}
{"Day":"19","Month":"Mar","Mo.Number":"3","Day_of_year":"79","Draft_No.":"200"}
{"Day":"20","Month":"Mar","Mo.Number":"3","Day_of_year":"80","Draft_No.":"239"}
{"Day":"21","Month":"Mar","Mo.Number":"3","Day_of_year":"81","Draft_No.":"334"}
{"Day":"22","Month":"Mar","Mo.Number":"3","Day_of_year":"82","Draft_No.":"265"}
{"Day":"23","Month":"Mar","Mo.Number":"3","Day_of_year":"83","Draft_No.":"256"}
{"Day":"24","Month":"Mar","Mo.Number":"3","Day_of_year":"84","Draft_No.":"258"}
{"Day":"25","Month":"Mar","Mo.Number":"3","Day_of_year":"85","Draft_No.":"343"}
{"Day":"26","Month":"Mar","Mo.Number":"3","Day_of_year":"86","Draft_No.":"170"}
{"Day":"27","Month":"Mar","Mo.Number":"3","Day_of_year":"87","Draft_No.":"268"}
{"Day":"28","Month":"Mar","Mo.Number":"3","Day_of_year":"88","Draft_No.":"223"}
{"Day":"29","Month":"Mar","Mo.Number":"3","Day_of_year":"89","Draft_No.":"362"}
{"Day":"30","Month":"Mar","Mo.Number":"3","Day_of_year":"90","Draft_No.":"217"}
{"Day":"31","Month":"Mar","Mo.Number":"3","Day_of_year":"91","Draft_No.":"30"}
{"Day":"1","Month":"Apr","Mo.Number":"4","Day_of_year":"92","Draft_No.":"32"}
{"Day":"2","Month":"Apr","Mo.Number":"4","Day_of_year":"93","Draft_No.":"271"}
{"Day":"3","Month":"Apr","Mo.Number":"4","Day_of_year":"94","Draft_No.":"83"}
{"Day":"4","Month":"Apr","Mo.Number":"4","Day_of_year":"95","Draft_No.":"81"}
{"Day":"5","Month":"Apr","Mo.Number":"4","Day_of_year":"96","Draft_No.":"269"}
{"Day":"6","Month":"Apr","Mo.Number":"4","Day_of_year":"97","Draft_No.":"253"}
{"Day":"7","Month":"Apr","Mo.Number":"4","Day_of_year":"98","Draft_No.":"147"}
{"Day":"8","Month":"Apr","Mo.Number":"4","Day_of_year":"99","Draft_No.":"312"}
{"Day":"9","Month":"Apr","Mo.Number":"4","Day_of_year":"100","Draft_No.":"219"}
{"Day":"10","Month":"Apr","Mo.Number":"4","Day_of_year":"101","Draft_No.":"218"}
{"Day":"11","Month":"Apr","Mo.Number":"4","Day_of_year":"102","Draft_No.":"14"}
{"Day":"12","Month":"Apr","Mo.Number":"4","Day_of_year":"103","Draft_No.":"346"}
{"Day":"13","Month":"Apr","Mo.Number":"4","Day_of_year":"104","Draft_No.":"124"}
{"Day":"14","Month":"Apr","Mo.Number":"4","Day_of_year":"105","Draft_No.":"231"}
{"Day":"15","Month":"Apr","Mo.Number":"4","Day_of_year":"106","Draft_No.":"273"}
{"Day":"16","Month":"Apr","Mo.Number":"4","Day_of_year":"107","Draft_No.":"148"}
{"Day":"17","Month":"Apr","Mo.Number":"4","Day_of_year":"108","Draft_No.":"260"}
{"Day":"18","Month":"Apr","Mo.Number":"4","Day_of_year":"109","Draft_No.":"90"}
{"Day":"19","Month":"Apr","Mo.Number":"4","Day_of_year":"110","Draft_No.":"336"}
{"Day":"20","Month":"Apr","Mo.Number":"4","Day_of_year":"111","Draft_No.":"345"}
{"Day":"21","Month":"Apr","Mo.Number":"4","Day_of_year":"112","Draft_No.":"62"}
{"Day":"22","Month":"Apr","Mo.Number":"4","Day_of_year":"113","Draft_No.":"316"}
{"Day":"23","Month":"Apr","Mo.Number":"4","Day_of_year":"114","Draft_No.":"252"}
{"Day":"24","Month":"Apr","Mo.Number":"4","Day_of_year":"115","Draft_No.":"2"}
{"Day":"25","Month":"Apr","Mo.Number":"4","Day_of_year":"116","Draft_No.":"351"}
{"Day":"26","Month":"Apr","Mo.Number":"4","Day_of_year":"117","Draft_No.":"340"}
{"Day":"27","Month":"Apr","Mo.Number":"4","Day_of_year":"118","Draft_No.":"74"}
{"Day":"28","Month":"Apr","Mo.Number":"4","Day_of_year":"119","Draft_No.":"262"}
{"Day":"29","Month":"Apr","Mo.Number":"4","Day_of_year":"120","Draft_No.":"191"}
{"Day":"30","Month":"Apr","Mo.Number":"4","Day_of_year":"121","Draft_No.":"208"}
{"Day":"1","Month":"May","Mo.Number":"5","Day_of_year":"122","Draft_No.":"330"}
{"Day":"2","Month":"May","Mo.Number":"5","Day_of_year":"123","Draft_No.":"298"}
{"Day":"3","Month":"May","Mo.Number":"5","Day_of_year":"124","Draft_No.":"40"}
{"Day":"4","Month":"May","Mo.Number":"5","Day_of_year":"125","Draft_No.":"276"}
{"Day":"5","Month":"May","Mo.Number":"5","Day_of_year":"126","Draft_No.":"364"}
{"Day":"6","Month":"May","Mo.Number":"5","Day_of_year":"127","Draft_No.":"155"}
{"Day":"7","Month":"May","Mo.Number":"5","Day_of_year":"128","Draft_No.":"35"}
{"Day":"8","Month":"May","Mo.Number":"5","Day_of_year":"129","Draft_No.":"321"}
{"Day":"9","Month":"May","Mo.Number":"5","Day_of_year":"130","Draft_No.":"197"}
{"Day":"10","Month":"May","Mo.Number":"5","Day_of_year":"131","Draft_No.":"65"}
{"Day":"11","Month":"May","Mo.Number":"5","Day_of_year":"132","Draft_No.":"37"}
{"Day":"12","Month":"May","Mo.Number":"5","Day_of_year":"133","Draft_No.":"133"}
{"Day":"13","Month":"May","Mo.Number":"5","Day_of_year":"134","Draft_No.":"295"}
{"Day":"14","Month":"May","Mo.Number":"5","Day_of_year":"135","Draft_No.":"178"}
{"Day":"15","Month":"May","Mo.Number":"5","Day_of_year":"136","Draft_No.":"130"}
{"Day":"16","Month":"May","Mo.Number":"5","Day_of_year":"137","Draft_No.":"55"}
{"Day":"17","Month":"May","Mo.Number":"5","Day_of_year":"138","Draft_No.":"112"}
{"Day":"18","Month":"May","Mo.Number":"5","Day_of_year":"139","Draft_No.":"278"}
{"Day":"19","Month":"May","Mo.Number":"5","Day_of_year":"140","Draft_No.":"75"}
{"Day":"20","Month":"May","Mo.Number":"5","Day_of_year":"141","Draft_No.":"183"}
{"Day":"21","Month":"May","Mo.Number":"5","Day_of_year":"142","Draft_No.":"250"}
{"Day":"22","Month":"May","Mo.Number":"5","Day_of_year":"143","Draft_No.":"326"}
{"Day":"23","Month":"May","Mo.Number":"5","Day_of_year":"144","Draft_No.":"319"}
{"Day":"24","Month":"May","Mo.Number":"5","Day_of_year":"145","Draft_No.":"31"}
{"Day":"25","Month":"May","Mo.Number":"5","Day_of_year":"146","Draft_No.":"361"}
{"Day":"26","Month":"May","Mo.Number":"5","Day_of_year":"147","Draft_No.":"357"}
{"Day":"27","Month":"May","Mo.Number":"5","Day_of_year":"148","Draft_No.":"296"}
{"Day":"28","Month":"May","Mo.Number":"5","Day_of_year":"149","Draft_No.":"308"}
{"Day":"29","Month":"May","Mo.Number":"5","Day_of_year":"150","Draft_No.":"226"}
{"Day":"30","Month":"May","Mo.Number":"5","Day_of_year":"151","Draft_No.":"103"}
{"Day":"31","Month":"May","Mo.Number":"5","Day_of_year":"152","Draft_No.":"313"}
{"Day":"1","Month":"Jun","Mo.Number":"6","Day_of_year":"153","Draft_No.":"249"}
{"Day":"2","Month":"Jun","Mo.Number":"6","Day_of_year":"154","Draft_No.":"228"}
{"Day":"3","Month":"Jun","Mo.Number":"6","Day_of_year":"155","Draft_No.":"301"}
{"Day":"4","Month":"Jun","Mo.Number":"6","Day_of_year":"156","Draft_No.":"20"}
{"Day":"5","Month":"Jun","Mo.Number":"6","Day_of_year":"157","Draft_No.":"28"}
{"Day":"6","Month":"Jun","Mo.Number":"6","Day_of_year":"158","Draft_No.":"110"}
{"Day":"7","Month":"Jun","Mo.Number":"6","Day_of_year":"159","Draft_No.":"85"}
{"Day":"8","Month":"Jun","Mo.Number":"6","Day_of_year":"160","Draft_No.":"366"}
{"Day":"9","Month":"Jun","Mo.Number":"6","Day_of_year":"161","Draft_No.":"335"}
{"Day":"10","Month":"Jun","Mo.Number":"6","Day_of_year":"162","Draft_No.":"206"}
{"Day":"11","Month":"Jun","Mo.Number":"6","Day_of_year":"163","Draft_No.":"134"}
{"Day":"12","Month":"Jun","Mo.Number":"6","Day_of_year":"164","Draft_No.":"272"}
{"Day":"13","Month":"Jun","Mo.Number":"6","Day_of_year":"165","Draft_No.":"69"}
{"Day":"14","Month":"Jun","Mo.Number":"6","Day_of_year":"166","Draft_No.":"356"}
{"Day":"15","Month":"Jun","Mo.Number":"6","Day_of_year":"167","Draft_No.":"180"}
{"Day":"16","Month":"Jun","Mo.Number":"6","Day_of_year":"168","Draft_No.":"274"}
{"Day":"17","Month":"Jun","Mo.Number":"6","Day_of_year":"169","Draft_No.":"73"}
{"Day":"18","Month":"Jun","Mo.Number":"6","Day_of_year":"170","Draft_No.":"341"}
{"Day":"19","Month":"Jun","Mo.Number":"6","Day_of_year":"171","Draft_No.":"104"}
{"Day":"20","Month":"Jun","Mo.Number":"6","Day_of_year":"172","Draft_No.":"360"}
{"Day":"21","Month":"Jun","Mo.Number":"6","Day_of_year":"173","Draft_No.":"60"}
{"Day":"22","Month":"Jun","Mo.Number":"6","Day_of_year":"174","Draft_No.":"247"}
{"Day":"23","Month":"Jun","Mo.Number":"6","Day_of_year":"175","Draft_No.":"109"}
{"Day":"24","Month":"Jun","Mo.Number":"6","Day_of_year":"176","Draft_No.":"358"}
{"Day":"25","Month":"Jun","Mo.Number":"6","Day_of_year":"177","Draft_No.":"137"}
{"Day":"26","Month":"Jun","Mo.Number":"6","Day_of_year":"178","Draft_No.":"22"}
{"Day":"27","Month":"Jun","Mo.Number":"6","Day_of_year":"179","Draft_No.":"64"}
{"Day":"28","Month":"Jun","Mo.Number":"6","Day_of_year":"180","Draft_No.":"222"}
{"Day":"29","Month":"Jun","Mo.Number":"6","Day_of_year":"181","Draft_No.":"353"}
{"Day":"30","Month":"Jun","Mo.Number":"6","Day_of_year":"182","Draft_No.":"209"}
{"Day":"1","Month":"Jul","Mo.Number":"7","Day_of_year":"183","Draft_No.":"93"}
{"Day":"2","Month":"Jul","Mo.Number":"7","Day_of_year":"184","Draft_No.":"350"}
{"Day":"3","Month":"Jul","Mo.Number":"7","Day_of_year":"185","Draft_No.":"115"}
{"Day":"4","Month":"Jul","Mo.Number":"7","Day_of_year":"186","Draft_No.":"279"}
{"Day":"5","Month":"Jul","Mo.Number":"7","Day_of_year":"187","Draft_No.":"188"}
{"Day":"6","Month":"Jul","Mo.Number":"7","Day_of_year":"188","Draft_No.":"327"}
{"Day":"7","Month":"Jul","Mo.Number":"7","Day_of_year":"189","Draft_No.":"50"}
{"Day":"8","Month":"Jul","Mo.Number":"7","Day_of_year":"190","Draft_No.":"13"}
{"Day":"9","Month":"Jul","Mo.Number":"7","Day_of_year":"191","Draft_No.":"277"}
{"Day":"10","Month":"Jul","Mo.Number":"7","Day_of_year":"192","Draft_No.":"284"}
{"Day":"11","Month":"Jul","Mo.Number":"7","Day_of_year":"193","Draft_No.":"248"}
{"Day":"12","Month":"Jul","Mo.Number":"7","Day_of_year":"194","Draft_No.":"15"}
{"Day":"13","Month":"Jul","Mo.Number":"7","Day_of_year":"195","Draft_No.":"42"}
{"Day":"14","Month":"Jul","Mo.Number":"7","Day_of_year":"196","Draft_No.":"331"}
{"Day":"15","Month":"Jul","Mo.Number":"7","Day_of_year":"197","Draft_No.":"322"}
{"Day":"16","Month":"Jul","Mo.Number":"7","Day_of_year":"198","Draft_No.":"120"}
{"Day":"17","Month":"Jul","Mo.Number":"7","Day_of_year":"199","Draft_No.":"98"}
{"Day":"18","Month":"Jul","Mo.Number":"7","Day_of_year":"200","Draft_No.":"190"}
{"Day":"19","Month":"Jul","Mo.Number":"7","Day_of_year":"201","Draft_No.":"227"}
{"Day":"20","Month":"Jul","Mo.Number":"7","Day_of_year":"202","Draft_No.":"187"}
{"Day":"21","Month":"Jul","Mo.Number":"7","Day_of_year":"203","Draft_No.":"27"}
{"Day":"22","Month":"Jul","Mo.Number":"7","Day_of_year":"204","Draft_No.":"153"}
{"Day":"23","Month":"Jul","Mo.Number":"7","Day_of_year":"205","Draft_No.":"172"}
{"Day":"24","Month":"Jul","Mo.Number":"7","Day_of_year":"206","Draft_No.":"23"}
{"Day":"25","Month":"Jul","Mo.Number":"7","Day_of_year":"207","Draft_No.":"67"}
{"Day":"26","Month":"Jul","Mo.Number":"7","Day_of_year":"208","Draft_No.":"303"}
{"Day":"27","Month":"Jul","Mo.Number":"7","Day_of_year":"209","Draft_No.":"289"}
{"Day":"28","Month":"Jul","Mo.Number":"7","Day_of_year":"210","Draft_No.":"88"}
{"Day":"29","Month":"Jul","Mo.Number":"7","Day_of_year":"211","Draft_No.":"270"}
{"Day":"30","Month":"Jul","Mo.Number":"7","Day_of_year":"212","Draft_No.":"287"}
{"Day":"31","Month":"Jul","Mo.Number":"7","Day_of_year":"213","Draft_No.":"193"}
{"Day":"1","Month":"Aug","Mo.Number":"8","Day_of_year":"214","Draft_No.":"111"}
{"Day":"2","Month":"Aug","Mo.Number":"8","Day_of_year":"215","Draft_No.":"45"}
{"Day":"3","Month":"Aug","Mo.Number":"8","Day_of_year":"216","Draft_No.":"261"}
{"Day":"4","Month":"Aug","Mo.Number":"8","Day_of_year":"217","Draft_No.":"145"}
{"Day":"5","Month":"Aug","Mo.Number":"8","Day_of_year":"218","Draft_No.":"54"}
{"Day":"6","Month":"Aug","Mo.Number":"8","Day_of_year":"219","Draft_No.":"114"}
{"Day":"7","Month":"Aug","Mo.Number":"8","Day_of_year":"220","Draft_No.":"168"}
{"Day":"8","Month":"Aug","Mo.Number":"8","Day_of_year":"221","Draft_No.":"48"}
{"Day":"9","Month":"Aug","Mo.Number":"8","Day_of_year":"222","Draft_No.":"106"}
{"Day":"10","Month":"Aug","Mo.Number":"8","Day_of_year":"223","Draft_No.":"21"}
{"Day":"11","Month":"Aug","Mo.Number":"8","Day_of_year":"224","Draft_No.":"324"}
{"Day":"12","Month":"Aug","Mo.Number":"8","Day_of_year":"225","Draft_No.":"142"}
{"Day":"13","Month":"Aug","Mo.Number":"8","Day_of_year":"226","Draft_No.":"307"}
{"Day":"14","Month":"Aug","Mo.Number":"8","Day_of_year":"227","Draft_No.":"198"}
{"Day":"15","Month":"Aug","Mo.Number":"8","Day_of_year":"228","Draft_No.":"102"}
{"Day":"16","Month":"Aug","Mo.Number":"8","Day_of_year":"229","Draft_No.":"44"}
{"Day":"17","Month":"Aug","Mo.Number":"8","Day_of_year":"230","Draft_No.":"154"}
{"Day":"18","Month":"Aug","Mo.Number":"8","Day_of_year":"231","Draft_No.":"141"}
{"Day":"19","Month":"Aug","Mo.Number":"8","Day_of_year":"232","Draft_No.":"311"}
{"Day":"20","Month":"Aug","Mo.Number":"8","Day_of_year":"233","Draft_No.":"344"}
{"Day":"21","Month":"Aug","Mo.Number":"8","Day_of_year":"234","Draft_No.":"291"}
{"Day":"22","Month":"Aug","Mo.Number":"8","Day_of_year":"235","Draft_No.":"339"}
{"Day":"23","Month":"Aug","Mo.Number":"8","Day_of_year":"236","Draft_No.":"116"}
{"Day":"24","Month":"Aug","Mo.Number":"8","Day_of_year":"237","Draft_No.":"36"}
{"Day":"25","Month":"Aug","Mo.Number":"8","Day_of_year":"238","Draft_No.":"286"}
{"Day":"26","Month":"Aug","Mo.Number":"8","Day_of_year":"239","Draft_No.":"245"}
{"Day":"27","Month":"Aug","Mo.Number":"8","Day_of_year":"240","Draft_No.":"352"}
{"Day":"28","Month":"Aug","Mo.Number":"8","Day_of_year":"241","Draft_No.":"167"}
{"Day":"29","Month":"Aug","Mo.Number":"8","Day_of_year":"242","Draft_No.":"61"}
{"Day":"30","Month":"Aug","Mo.Number":"8","Day_of_year":"243","Draft_No.":"333"}
{"Day":"31","Month":"Aug","Mo.Number":"8","Day_of_year":"244","Draft_No.":"11"}
{"Day":"1","Month":"Sep","Mo.Number":"9","Day_of_year":"245","Draft_No.":"225"}
{"Day":"2","Month":"Sep","Mo.Number":"9","Day_of_year":"246","Draft_No.":"161"}
{"Day":"3","Month":"Sep","Mo.Number":"9","Day_of_year":"247","Draft_No.":"49"}
{"Day":"4","Month":"Sep","Mo.Number":"9","Day_of_year":"248","Draft_No.":"232"}
{"Day":"5","Month":"Sep","Mo.Number":"9","Day_of_year":"249","Draft_No.":"82"}
{"Day":"6","Month":"Sep","Mo.Number":"9","Day_of_year":"250","Draft_No.":"6"}
{"Day":"7","Month":"Sep","Mo.Number":"9","Day_of_year":"251","Draft_No.":"8"}
{"Day":"8","Month":"Sep","Mo.Number":"9","Day_of_year":"252","Draft_No.":"184"}
{"Day":"9","Month":"Sep","Mo.Number":"9","Day_of_year":"253","Draft_No.":"263"}
{"Day":"10","Month":"Sep","Mo.Number":"9","Day_of_year":"254","Draft_No.":"71"}
{"Day":"11","Month":"Sep","Mo.Number":"9","Day_of_year":"255","Draft_No.":"158"}
{"Day":"12","Month":"Sep","Mo.Number":"9","Day_of_year":"256","Draft_No.":"242"}
{"Day":"13","Month":"Sep","Mo.Number":"9","Day_of_year":"257","Draft_No.":"175"}
{"Day":"14","Month":"Sep","Mo.Number":"9","Day_of_year":"258","Draft_No.":"1"}
{"Day":"15","Month":"Sep","Mo.Number":"9","Day_of_year":"259","Draft_No.":"113"}
{"Day":"16","Month":"Sep","Mo.Number":"9","Day_of_year":"260","Draft_No.":"207"}
{"Day":"17","Month":"Sep","Mo.Number":"9","Day_of_year":"261","Draft_No.":"255"}
{"Day":"18","Month":"Sep","Mo.Number":"9","Day_of_year":"262","Draft_No.":"246"}
{"Day":"19","Month":"Sep","Mo.Number":"9","Day_of_year":"263","Draft_No.":"177"}
{"Day":"20","Month":"Sep","Mo.Number":"9","Day_of_year":"264","Draft_No.":"63"}
{"Day":"21","Month":"Sep","Mo.Number":"9","Day_of_year":"265","Draft_No.":"204"}
{"Day":"22","Month":"Sep","Mo.Number":"9","Day_of_year":"266","Draft_No.":"160"}
{"Day":"23","Month":"Sep","Mo.Number":"9","Day_of_year":"267","Draft_No.":"119"}
{"Day":"24","Month":"Sep","Mo.Number":"9","Day_of_year":"268","Draft_No.":"195"}
{"Day":"25","Month":"Sep","Mo.Number":"9","Day_of_year":"269","Draft_No.":"149"}
{"Day":"26","Month":"Sep","Mo.Number":"9","Day_of_year":"270","Draft_No.":"18"}
{"Day":"27","Month":"Sep","Mo.Number":"9","Day_of_year":"271","Draft_No.":"233"}
{"Day":"28","Month":"Sep","Mo.Number":"9","Day_of_year":"272","Draft_No.":"257"}
{"Day":"29","Month":"Sep","Mo.Number":"9","Day_of_year":"273","Draft_No.":"151"}
{"Day":"30","Month":"Sep","Mo.Number":"9","Day_of_year":"274","Draft_No.":"315"}
{"Day":"1","Month":"Oct","Mo.Number":"10","Day_of_year":"275","Draft_No.":"359"}
{"Day":"2","Month":"Oct","Mo.Number":"10","Day_of_year":"276","Draft_No.":"125"}
{"Day":"3","Month":"Oct","Mo.Number":"10","Day_of_year":"277","Draft_No.":"244"}
{"Day":"4","Month":"Oct","Mo.Number":"10","Day_of_year":"278","Draft_No.":"202"}
{"Day":"5","Month":"Oct","Mo.Number":"10","Day_of_year":"279","Draft_No.":"24"}
{"Day":"6","Month":"Oct","Mo.Number":"10","Day_of_year":"280","Draft_No.":"87"}
{"Day":"7","Month":"Oct","Mo.Number":"10","Day_of_year":"281","Draft_No.":"234"}
{"Day":"8","Month":"Oct","Mo.Number":"10","Day_of_year":"282","Draft_No.":"283"}
{"Day":"9","Month":"Oct","Mo.Number":"10","Day_of_year":"283","Draft_No.":"342"}
{"Day":"10","Month":"Oct","Mo.Number":"10","Day_of_year":"284","Draft_No.":"220"}
{"Day":"11","Month":"Oct","Mo.Number":"10","Day_of_year":"285","Draft_No.":"237"}
{"Day":"12","Month":"Oct","Mo.Number":"10","Day_of_year":"286","Draft_No.":"72"}
{"Day":"13","Month":"Oct","Mo.Number":"10","Day_of_year":"287","Draft_No.":"138"}
{"Day":"14","Month":"Oct","Mo.Number":"10","Day_of_year":"288","Draft_No.":"294"}
{"Day":"15","Month":"Oct","Mo.Number":"10","Day_of_year":"289","Draft_No.":"171"}
{"Day":"16","Month":"Oct","Mo.Number":"10","Day_of_year":"290","Draft_No.":"254"}
{"Day":"17","Month":"Oct","Mo.Number":"10","Day_of_year":"291","Draft_No.":"288"}
{"Day":"18","Month":"Oct","Mo.Number":"10","Day_of_year":"292","Draft_No.":"5"}
{"Day":"19","Month":"Oct","Mo.Number":"10","Day_of_year":"293","Draft_No.":"241"}
{"Day":"20","Month":"Oct","Mo.Number":"10","Day_of_year":"294","Draft_No.":"192"}
{"Day":"21","Month":"Oct","Mo.Number":"10","Day_of_year":"295","Draft_No.":"243"}
{"Day":"22","Month":"Oct","Mo.Number":"10","Day_of_year":"296","Draft_No.":"117"}
{"Day":"23","Month":"Oct","Mo.Number":"10","Day_of_year":"297","Draft_No.":"201"}
{"Day":"24","Month":"Oct","Mo.Number":"10","Day_of_year":"298","Draft_No.":"196"}
{"Day":"25","Month":"Oct","Mo.Number":"10","Day_of_year":"299","Draft_No.":"176"}
{"Day":"26","Month":"Oct","Mo.Number":"10","Day_of_year":"300","Draft_No.":"7"}
{"Day":"27","Month":"Oct","Mo.Number":"10","Day_of_year":"301","Draft_No.":"264"}
{"Day":"28","Month":"Oct","Mo.Number":"10","Day_of_year":"302","Draft_No.":"94"}
{"Day":"29","Month":"Oct","Mo.Number":"10","Day_of_year":"303","Draft_No.":"229"}
{"Day":"30","Month":"Oct","Mo.Number":"10","Day_of_year":"304","Draft_No.":"38"}
{"Day":"31","Month":"Oct","Mo.Number":"10","Day_of_year":"305","Draft_No.":"79"}
{"Day":"1","Month":"Nov","Mo.Number":"11","Day_of_year":"306","Draft_No.":"19"}
{"Day":"2","Month":"Nov","Mo.Number":"11","Day_of_year":"307","Draft_No.":"34"}
{"Day":"3","Month":"Nov","Mo.Number":"11","Day_of_year":"308","Draft_No.":"348"}
{"Day":"4","Month":"Nov","Mo.Number":"11","Day_of_year":"309","Draft_No.":"266"}
{"Day":"5","Month":"Nov","Mo.Number":"11","Day_of_year":"310","Draft_No.":"310"}
{"Day":"6","Month":"Nov","Mo.Number":"11","Day_of_year":"311","Draft_No.":"76"}
{"Day":"7","Month":"Nov","Mo.Number":"11","Day_of_year":"312","Draft_No.":"51"}
{"Day":"8","Month":"Nov","Mo.Number":"11","Day_of_year":"313","Draft_No.":"97"}
{"Day":"9","Month":"Nov","Mo.Number":"11","Day_of_year":"314","Draft_No.":"80"}
{"Day":"10","Month":"Nov","Mo.Number":"11","Day_of_year":"315","Draft_No.":"282"}
{"Day":"11","Month":"Nov","Mo.Number":"11","Day_of_year":"316","Draft_No.":"46"}
{"Day":"12","Month":"Nov","Mo.Number":"11","Day_of_year":"317","Draft_No.":"66"}
{"Day":"13","Month":"Nov","Mo.Number":"11","Day_of_year":"318","Draft_No.":"126"}
{"Day":"14","Month":"Nov","Mo.Number":"11","Day_of_year":"319","Draft_No.":"127"}
{"Day":"15","Month":"Nov","Mo.Number":"11","Day_of_year":"320","Draft_No.":"131"}
{"Day":"16","Month":"Nov","Mo.Number":"11","Day_of_year":"321","Draft_No.":"107"}
{"Day":"17","Month":"Nov","Mo.Number":"11","Day_of_year":"322","Draft_No.":"143"}
{"Day":"18","Month":"Nov","Mo.Number":"11","Day_of_year":"323","Draft_No.":"146"}
{"Day":"19","Month":"Nov","Mo.Number":"11","Day_of_year":"324","Draft_No.":"203"}
{"Day":"20","Month":"Nov","Mo.Number":"11","Day_of_year":"325","Draft_No.":"185"}
{"Day":"21","Month":"Nov","Mo.Number":"11","Day_of_year":"326","Draft_No.":"156"}
{"Day":"22","Month":"Nov","Mo.Number":"11","Day_of_year":"327","Draft_No.":"9"}
{"Day":"23","Month":"Nov","Mo.Number":"11","Day_of_year":"328","Draft_No.":"182"}
{"Day":"24","Month":"Nov","Mo.Number":"11","Day_of_year":"329","Draft_No.":"230"}
{"Day":"25","Month":"Nov","Mo.Number":"11","Day_of_year":"330","Draft_No.":"132"}
{"Day":"26","Month":"Nov","Mo.Number":"11","Day_of_year":"331","Draft_No.":"309"}
{"Day":"27","Month":"Nov","Mo.Number":"11","Day_of_year":"332","Draft_No.":"47"}
{"Day":"28","Month":"Nov","Mo.Number":"11","Day_of_year":"333","Draft_No.":"281"}
{"Day":"29","Month":"Nov","Mo.Number":"11","Day_of_year":"334","Draft_No.":"99"}
{"Day":"30","Month":"Nov","Mo.Number":"11","Day_of_year":"335","Draft_No.":"174"}
{"Day":"1","Month":"Dec","Mo.Number":"12","Day_of_year":"336","Draft_No.":"129"}
{"Day":"2","Month":"Dec","Mo.Number":"12","Day_of_year":"337","Draft_No.":"328"}
{"Day":"3","Month":"Dec","Mo.Number":"12","Day_of_year":"338","Draft_No.":"157"}
{"Day":"4","Month":"Dec","Mo.Number":"12","Day_of_year":"339","Draft_No.":"165"}
{"Day":"5","Month":"Dec","Mo.Number":"12","Day_of_year":"340","Draft_No.":"56"}
{"Day":"6","Month":"Dec","Mo.Number":"12","Day_of_year":"341","Draft_No.":"10"}
{"Day":"7","Month":"Dec","Mo.Number":"12","Day_of_year":"342","Draft_No.":"12"}
{"Day":"8","Month":"Dec","Mo.Number":"12","Day_of_year":"343","Draft_No.":"105"}
{"Day":"9","Month":"Dec","Mo.Number":"12","Day_of_year":"344","Draft_No.":"43"}
{"Day":"10","Month":"Dec","Mo.Number":"12","Day_of_year":"345","Draft_No.":"41"}
{"Day":"11","Month":"Dec","Mo.Number":"12","Day_of_year":"346","Draft_No.":"39"}
{"Day":"12","Month":"Dec","Mo.Number":"12","Day_of_year":"347","Draft_No.":"314"}
{"Day":"13","Month":"Dec","Mo.Number":"12","Day_of_year":"348","Draft_No.":"163"}
{"Day":"14","Month":"Dec","Mo.Number":"12","Day_of_year":"349","Draft_No.":"26"}
{"Day":"15","Month":"Dec","Mo.Number":"12","Day_of_year":"350","Draft_No.":"320"}
{"Day":"16","Month":"Dec","Mo.Number":"12","Day_of_year":"351","Draft_No.":"96"}
{"Day":"17","Month":"Dec","Mo.Number":"12","Day_of_year":"352","Draft_No.":"304"}
{"Day":"18","Month":"Dec","Mo.Number":"12","Day_of_year":"353","Draft_No.":"128"}
{"Day":"19","Month":"Dec","Mo.Number":"12","Day_of_year":"354","Draft_No.":"240"}
{"Day":"20","Month":"Dec","Mo.Number":"12","Day_of_year":"355","Draft_No.":"135"}
{"Day":"21","Month":"Dec","Mo.Number":"12","Day_of_year":"356","Draft_No.":"70"}
{"Day":"22","Month":"Dec","Mo.Number":"12","Day_of_year":"357","Draft_No.":"53"}
{"Day":"23","Month":"Dec","Mo.Number":"12","Day_of_year":"358","Draft_No.":"162"}
{"Day":"24","Month":"Dec","Mo.Number":"12","Day_of_year":"359","Draft_No.":"95"}
{"Day":"25","Month":"Dec","Mo.Number":"12","Day_of_year":"360","Draft_No.":"84"}
{"Day":"26","Month":"Dec","Mo.Number":"12","Day_of_year":"361","Draft_No.":"173"}
{"Day":"27","Month":"Dec","Mo.Number":"12","Day_of_year":"362","Draft_No.":"78"}
{"Day":"28","Month":"Dec","Mo.Number":"12","Day_of_year":"363","Draft_No.":"123"}
{"Day":"29","Month":"Dec","Mo.Number":"12","Day_of_year":"364","Draft_No.":"16"}
{"Day":"30","Month":"Dec","Mo.Number":"12","Day_of_year":"365","Draft_No.":"3"}
{"Day":"31","Month":"Dec","Mo.Number":"12","Day_of_year":"366","Draft_No.":"100"}
"""

main(draft_data)
